# NLP3 - Prepocessing

---

### Introduction to Preprocessing in NLP with Python

Preprocessing is a vital step in natural language processing (NLP) that involves transforming raw text into a format suitable for analysis and modeling. This process enhances the quality of data by cleaning and standardizing it, enabling more accurate and efficient NLP tasks. In Python, several libraries, such as NLTK, and SpaCy, provide powerful tools for preprocessing text. Common techniques include lowercasing, tokenization, stop word removal, and stemming or lemmatization. By implementing these methods, practitioners can significantly improve the performance of their NLP models, ensuring that the data used for training and evaluation is relevant and well-structured. This study guide will explore key preprocessing techniques and demonstrate how to apply them using Python, laying a solid foundation for effective NLP projects.

---

1 - Discuss what a Corpus. What role does it play in Natural Language Processing?

In [1]:
#In NLP, a corpus is a large and structured collection of texts or linguistic data that serves as the foundation for various language processing tasks.
#It can consist of written texts, transcripts of spoken language, or any other source of language data.
#A corpus is used for training, testing, and evaluating NLP models by providing real-world examples of language usage.
#It can be general (covering a wide range of topics) or domain-specific (focused on a particular field, such as legal or medical texts),
#and is often annotated with linguistic information like part-of-speech tags or named entities to facilitate analysis and model building.

2 - Therefore, we need a [corpus](https://huggingface.co/datasets/tclopess/sinopsys_movies_portuguese) for our tests in today's class. We'll be working with a corpus of movie synopses in Portuguese. Below, you can see the code to load it.

In [2]:
#first lets install datasets library
# !pip install datasets

Requirement already satisfied: datasets in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (5.1.0)
Requirement already satisfied: filelock in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from datasets) (4.1.1)
Requirement already satisfied: numpy>=1.17 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from datasets) (2.5.4)
Requirement already satisfied: pyarrow>=24.0.0 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from datasets) (26.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from datasets) (3.0.6)
Requirement already satisfied: tqdm>=4.66.3 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from datasets) (4.70.1)
Requirement already satisfied: xxhash in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.7.0,>=2023.1.0 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (2026.7.0)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from datasets) (2.2.0)
Requirement already satisfied: packaging in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (3.14.5)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (1.7.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (2.13.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (4.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<8.0,>=4.5 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (7.1.0)
Requirement already satisfied: propcache>=0.2.0 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.25.1)
Requirement already satisfied: anyio>=4.10 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->datasets) (4.15.1)
Requirement already satisfied: httpcore2==2.13.1 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->datasets) (2.13.1)
Requirement already satisfied: idna>=3.18 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->datasets) (3.20)
Requirement already satisfied: truststore>=0.10 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->datasets) (0.10.5)
Requirement already satisfied: h11>=0.16 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from httpcore2==2.13.1->httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /Users/zuilpirola/PyCharmMiscProject/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [4]:
#import installed library
from datasets import load_dataset

#load dataset
dataset = load_dataset("tclopess/sinopsys_movies_portuguese")

#convert it to pandas and slice the first 3000 data points
df_sinop = dataset['train'].to_pandas()[:3000]
df_sinop.head()

,titulo,sinopse,generos,is_valid
0,We Were Soldiers,A história da primeira grande batalha da fase ...,"['Ação', 'História', 'Guerra']",False
1,4Got10,"Um negócio de drogas dá errado, deixando corpo...","['Ação', 'Crime', 'Thriller']",False
2,Pontypool,Quando o disc jockey Grant Mazzy se reporta à ...,"['Horror', 'Mistério', 'Ficção Científica']",False
3,Ticker,Depois que o parceiro de um detetive de São Fr...,"['Ação', 'Crime', 'Thriller']",False
4,Real Genius,Um adolescente prodígio tenso entra em uma fac...,"['Comédia', 'Romance', 'Ficção Científica']",True

In [5]:
len(df_sinop)

3000

In [6]:
df_sinop.head()

,titulo,sinopse,generos,is_valid
0,We Were Soldiers,A história da primeira grande batalha da fase ...,"['Ação', 'História', 'Guerra']",False
1,4Got10,"Um negócio de drogas dá errado, deixando corpo...","['Ação', 'Crime', 'Thriller']",False
2,Pontypool,Quando o disc jockey Grant Mazzy se reporta à ...,"['Horror', 'Mistério', 'Ficção Científica']",False
3,Ticker,Depois que o parceiro de um detetive de São Fr...,"['Ação', 'Crime', 'Thriller']",False
4,Real Genius,Um adolescente prodígio tenso entra em uma fac...,"['Comédia', 'Romance', 'Ficção Científica']",True

3 - Based on the corpus documentation and the representations above, what is the data unit or what does a document represent?

In [7]:
#Each document in the corpus above is a movie synopsis.

4 - Now that we have discussed what a corpus is and gained an understanding of the concept of documents within it, let's move on to preprocessing. The first step is to define what a token is. **A token is a single unit of text—such as a word, phrase, or symbol—that is treated as a distinct element during text processing.** In our case, we will define a token as a word and explore various methods for tokenizing documents. Please test tokenization using the following methods: regular expressions (regex), the NLTK library, the split function, and SpaCy.

In [8]:
df_sinop

,titulo,sinopse,generos,is_valid
0,We Were Soldiers,A história da primeira grande batalha da fase ...,"['Ação', 'História', 'Guerra']",False
1,4Got10,"Um negócio de drogas dá errado, deixando corpo...","['Ação', 'Crime', 'Thriller']",False
2,Pontypool,Quando o disc jockey Grant Mazzy se reporta à ...,"['Horror', 'Mistério', 'Ficção Científica']",False
3,Ticker,Depois que o parceiro de um detetive de São Fr...,"['Ação', 'Crime', 'Thriller']",False
4,Real Genius,Um adolescente prodígio tenso entra em uma fac...,"['Comédia', 'Romance', 'Ficção Científica']",True
...,...,...,...,...
2995,JGM (JanaGanaMana),"É o próximo filme em 3 de agosto, anunciado po...","['Ação', 'Drama']",False
2996,The Shootist,Um pistoleiro moribundo passa seus últimos dia...,"['Drama', 'Romance', 'Ocidental']",True
2997,Sleep Dealer,"Situado em um futuro próximo, mundo militariza...","['Drama', 'Ficção Científica', 'Thriller']",False
2998,Finding Neverland,Finding Neverland é um drama divertido sobre c...,['Drama'],False
2999,The Front Page,The Front Page é uma comédia do diretor Billy ...,['Comédia'],False

In [9]:
df_sinop['sinopse'].to_list()[0]

'A história da primeira grande batalha da fase americana da Guerra do Vietnã e os soldados de ambos os lados que a travaram.'

In [10]:
#using regex
import re

df_sinop['tokens_regex'] = df_sinop['sinopse'].str.findall(r'\w+')
df_sinop['tokens_regex'].to_list()[0]

['A',
 'história',
 'da',
 'primeira',
 'grande',
 'batalha',
 'da',
 'fase',
 'americana',
 'da',
 'Guerra',
 'do',
 'Vietnã',
 'e',
 'os',
 'soldados',
 'de',
 'ambos',
 'os',
 'lados',
 'que',
 'a',
 'travaram']

In [11]:
#using nltk
import nltk
nltk.download('punkt')

from nltk.tokenize import word_tokenize

df_sinop['tokens_nltk'] = df_sinop['sinopse'].apply(word_tokenize)
df_sinop['tokens_nltk'].to_list()[0]

[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1028)>

['A',
 'história',
 'da',
 'primeira',
 'grande',
 'batalha',
 'da',
 'fase',
 'americana',
 'da',
 'Guerra',
 'do',
 'Vietnã',
 'e',
 'os',
 'soldados',
 'de',
 'ambos',
 'os',
 'lados',
 'que',
 'a',
 'travaram',
 '.']

In [12]:
#teste usando split
df_sinop['tokens_split'] = df_sinop['sinopse'].str.split()
df_sinop['tokens_split'].to_list()[0]

['A',
 'história',
 'da',
 'primeira',
 'grande',
 'batalha',
 'da',
 'fase',
 'americana',
 'da',
 'Guerra',
 'do',
 'Vietnã',
 'e',
 'os',
 'soldados',
 'de',
 'ambos',
 'os',
 'lados',
 'que',
 'a',
 'travaram.']

In [95]:
# !python -m spacy download pt_core_news_lg

In [13]:
#using spacy

import spacy

nlp = spacy.load("pt_core_news_lg")
# nlp = spacy.load("pt_core_news_sm")

df_sinop['tokens_spacy'] = df_sinop['sinopse'].apply(lambda x: [x.text for x in nlp(x)])
df_sinop.loc[0,'tokens_spacy']

['A',
 'história',
 'da',
 'primeira',
 'grande',
 'batalha',
 'da',
 'fase',
 'americana',
 'da',
 'Guerra',
 'do',
 'Vietnã',
 'e',
 'os',
 'soldados',
 'de',
 'ambos',
 'os',
 'lados',
 'que',
 'a',
 'travaram',
 '.']

In [24]:
import string

a = "O Sr. João é um bom homem. Ele gosta de estudar NLP."

print("word_tokenize = ", word_tokenize(a))
print("Regex = ", re.findall(r'\w+',a))
print("Split = ", a.split())
print("Spacy = ", [x.text for x in nlp(a)])

word_tokenize =  ['O', 'Sr.', 'João', 'é', 'um', 'bom', 'homem', '.', 'Ele', 'gosta', 'de', 'estudar', 'NLP', '.']
Regex =  ['O', 'Sr', 'João', 'é', 'um', 'bom', 'homem', 'Ele', 'gosta', 'de', 'estudar', 'NLP']
Split =  ['O', 'Sr.', 'João', 'é', 'um', 'bom', 'homem.', 'Ele', 'gosta', 'de', 'estudar', 'NLP.']
Spacy =  ['O', 'Sr.', 'João', 'é', 'um', 'bom', 'homem', '.', 'Ele', 'gosta', 'de', 'estudar', 'NLP', '.']

5 - Based on the results above, do the functions perform the same task? Which one is better? Which is more efficient? Which one would you choose? What is the outcome of the approaches above when applied to the string `Estudamos NLP na quarta-feira. É importante você praticar.`?

In [25]:
#teste as opçoes acima com a frase
#Estudamos NLP na quarta-feira.

text = "Estudamos NLP na quarta-feira. É importante você praticar."

print("word_tokenize = ", word_tokenize(text))
print("Regex = ", re.findall(r'\w+',text))
print("Split = ", text.split())
print("Spacy = ", [x.text for x in nlp(text)])

word_tokenize =  ['Estudamos', 'NLP', 'na', 'quarta-feira', '.', 'É', 'importante', 'você', 'praticar', '.']
Regex =  ['Estudamos', 'NLP', 'na', 'quarta', 'feira', 'É', 'importante', 'você', 'praticar']
Split =  ['Estudamos', 'NLP', 'na', 'quarta-feira.', 'É', 'importante', 'você', 'praticar.']
Spacy =  ['Estudamos', 'NLP', 'na', 'quarta-feira', '.', 'É', 'importante', 'você', 'praticar', '.']

6 - You have already explored different tokenization approaches. We now want to expand the corpus preprocessing. Choose the approach that yielded the best results so far, and in addition to tokenizing, remove the stopwords. Use the stopwords provided by the NLTK library, and ensure that all tokens are converted to lowercase before removing them.

In [26]:
#usando nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop = list(set(stopwords.words('portuguese')))
print(stop)

import string
# Storing the sets of punctuation in variable result
pontuacoes = string.punctuation
print(pontuacoes)

['nossa', 'seu', 'pelas', 'sua', 'às', 'esta', 'aquela', 'tém', 'fôramos', 'seriam', 'já', 'teríamos', 'os', 'minhas', 'teria', 'estivermos', 'nossas', 'pelos', 'serão', 'eu', 'em', 'formos', 'numa', 'com', 'muito', 'num', 'houverem', 'estas', 'estive', 'são', 'houveríamos', 'tivemos', 'na', 'meus', 'estivemos', 'houvermos', 'dele', 'e', 'foi', 'que', 'sejam', 'nos', 'seria', 'fossem', 'aos', 'fomos', 'é', 'nas', 'houver', 'seus', 'estão', 'teus', 'houverei', 'tivéramos', 'vos', 'tiveram', 'no', 'terão', 'nossos', 'elas', 'estiveram', 'houveriam', 'estivéssemos', 'teriam', 'lhe', 'dela', 'hão', 'estavam', 'isto', 'está', 'pela', 'te', 'hajam', 'temos', 'tive', 'sem', 'houverá', 'vocês', 'nem', 'entre', 'houveremos', 'hei', 'estejamos', 'essa', 'houvéramos', 'teve', 'terei', 'uma', 'a', 'mas', 'tu', 'tiverem', 'tem', 'aquelas', 'terá', 'estamos', 'eles', 'tenha', 'somos', 'me', 'estou', 'esteja', 'tivesse', 'estivera', 'ser', 'hajamos', 'como', 'fui', 'essas', 'quando', 'tenham', 'teremos', 'eram', 'forem', 'tua', 'estávamos', 'tivermos', 'meu', 'houveria', 'pelo', 'tiver', 'estava', 'haver', 'suas', 'aqueles', 'deles', 'fosse', 'de', 'da', 'para', 'se', 'você', 'as', 'houvesse', 'esses', 'sou', 'tuas', 'lhes', 'ele', 'estivesse', 'qual', 'estivéramos', 'esteve', 'à', 'sejamos', 'houvessem', 'este', 'tivera', 'fora', 'foram', 'aquele', 'era', 'mesmo', 'também', 'estes', 'tenho', 'ou', 'estiver', 'nosso', 'tenhamos', 'ela', 'houverão', 'tivéssemos', 'estejam', 'seremos', 'teu', 'será', 'haja', 'havemos', 'serei', 'éramos', 'fôssemos', 'houvera', 'até', 'por', 'tinham', 'quem', 'seja', 'um', 'aquilo', 'estar', 'tinha', 'tivessem', 'das', 'do', 'dos', 'delas', 'houve', 'esse', 'depois', 'há', 'houvéssemos', 'não', 'seríamos', 'for', 'nós', 'tínhamos', 'mais', 'houvemos', 'houveram', 'só', 'estiverem', 'estivessem', 'minha', 'o', 'isso', 'ao']
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1028)>

In [29]:
#using nltk
import nltk
# nltk.download('punkt')

from nltk.tokenize import word_tokenize

df_sinop['tokens_nltk'] = df_sinop['sinopse'].apply(lambda y: [x.lower() for x in word_tokenize(y) if x.lower() not in stop and x.lower() not in pontuacoes])
df_sinop.loc[0,'tokens_nltk']

['história',
 'primeira',
 'grande',
 'batalha',
 'fase',
 'americana',
 'guerra',
 'vietnã',
 'soldados',
 'ambos',
 'lados',
 'travaram']

In [30]:
df_sinop

,titulo,sinopse,generos,is_valid,tokens_regex,tokens_nltk,tokens_split,tokens_spacy
0,We Were Soldiers,A história da primeira grande batalha da fase ...,"['Ação', 'História', 'Guerra']",False,"[A, história, da, primeira, grande, batalha, d...","[história, primeira, grande, batalha, fase, am...","[A, história, da, primeira, grande, batalha, d...","[A, história, da, primeira, grande, batalha, d..."
1,4Got10,"Um negócio de drogas dá errado, deixando corpo...","['Ação', 'Crime', 'Thriller']",False,"[Um, negócio, de, drogas, dá, errado, deixando...","[negócio, drogas, dá, errado, deixando, corpos...","[Um, negócio, de, drogas, dá, errado,, deixand...","[Um, negócio, de, drogas, dá, errado, ,, deixa..."
2,Pontypool,Quando o disc jockey Grant Mazzy se reporta à ...,"['Horror', 'Mistério', 'Ficção Científica']",False,"[Quando, o, disc, jockey, Grant, Mazzy, se, re...","[disc, jockey, grant, mazzy, reporta, estação,...","[Quando, o, disc, jockey, Grant, Mazzy, se, re...","[Quando, o, disc, jockey, Grant, Mazzy, se, re..."
3,Ticker,Depois que o parceiro de um detetive de São Fr...,"['Ação', 'Crime', 'Thriller']",False,"[Depois, que, o, parceiro, de, um, detetive, d...","[parceiro, detetive, francisco, assassinado, t...","[Depois, que, o, parceiro, de, um, detetive, d...","[Depois, que, o, parceiro, de, um, detetive, d..."
4,Real Genius,Um adolescente prodígio tenso entra em uma fac...,"['Comédia', 'Romance', 'Ficção Científica']",True,"[Um, adolescente, prodígio, tenso, entra, em, ...","[adolescente, prodígio, tenso, entra, faculdad...","[Um, adolescente, prodígio, tenso, entra, em, ...","[Um, adolescente, prodígio, tenso, entra, em, ..."
...,...,...,...,...,...,...,...,...
2995,JGM (JanaGanaMana),"É o próximo filme em 3 de agosto, anunciado po...","['Ação', 'Drama']",False,"[É, o, próximo, filme, em, 3, de, agosto, anun...","[próximo, filme, 3, agosto, anunciado, vijay, ...","[É, o, próximo, filme, em, 3, de, agosto,, anu...","[É, o, próximo, filme, em, 3, de, agosto, ,, a..."
2996,The Shootist,Um pistoleiro moribundo passa seus últimos dia...,"['Drama', 'Romance', 'Ocidental']",True,"[Um, pistoleiro, moribundo, passa, seus, últim...","[pistoleiro, moribundo, passa, últimos, dias, ...","[Um, pistoleiro, moribundo, passa, seus, últim...","[Um, pistoleiro, moribundo, passa, seus, últim..."
2997,Sleep Dealer,"Situado em um futuro próximo, mundo militariza...","['Drama', 'Ficção Científica', 'Thriller']",False,"[Situado, em, um, futuro, próximo, mundo, mili...","[situado, futuro, próximo, mundo, militarizado...","[Situado, em, um, futuro, próximo,, mundo, mil...","[Situado, em, um, futuro, próximo, ,, mundo, m..."
2998,Finding Neverland,Finding Neverland é um drama divertido sobre c...,['Drama'],False,"[Finding, Neverland, é, um, drama, divertido, ...","[finding, neverland, drama, divertido, sobre, ...","[Finding, Neverland, é, um, drama, divertido, ...","[Finding, Neverland, é, um, drama, divertido, ..."
2999,The Front Page,The Front Page é uma comédia do diretor Billy ...,['Comédia'],False,"[The, Front, Page, é, uma, comédia, do, direto...","[the, front, page, comédia, diretor, billy, wi...","[The, Front, Page, é, uma, comédia, do, direto...","[The, Front, Page, é, uma, comédia, do, direto..."

7 - In addition to tokenizing, applying lowercase, and removing stopwords, we can also use techniques like lemmatization and stemming. Test both methods on the following string: `Amo amar quem ama. O amor é uma grande virtude. Virtuosas são as pessoas que amam.` For lemmatization, I recommend using the Spacy library, and for stemming, the Snowball library.

In [32]:
#há também outra maneiras de preprocessar textos mas aqui vou destacar
#Lemmatizer
text = "Amo amar quem ama. O amor é uma grande virtude. Virtuosas são as pessoas que amam."
print([x.lemma_.lower() for x in nlp(text)])
# print(set([x.lemma_.lower() for x in nlp(text)]))

['amar', 'amar', 'quem', 'amar', '.', 'o', 'amor', 'ser', 'um', 'grande', 'virtude', '.', 'virtuosas', 'ser', 'o', 'pessoa', 'que', 'amar', '.']

In [55]:
#stemmer
from nltk.stem.snowball import SnowballStemmer
snow_stemmer = SnowballStemmer(language='portuguese')

text = "Amo amar quem ama. O amor é uma grande virtude. Virtuosas são as pessoas que amam."
print([snow_stemmer.stem(x.text) for x in nlp(text)])

['amo', 'amar', 'quem', 'ama', '.', 'o', 'amor', 'é', 'uma', 'grand', 'virtud', '.', 'virtuos', 'sã', 'as', 'pesso', 'que', 'amam', '.']

8 - Is there a better approach? Reflect on when to use lemmas versus stems in NLP.

In [56]:
# Use Stemming when:
# Speed is a priority.
# The application can tolerate some inaccuracies in word forms.
# The focus is on keyword extraction and search functionalities.


# Use Lemmatization when:
# The application demands a deeper understanding of language context.
# Accurate interpretations of words are essential for tasks like semantic analysis.
# You are working with complex sentences where the meaning significantly depends on the exact word form.

9 - Based on the conclusions drawn above, continue processing the corpus. In addition to the steps you have already applied, also implement lemmatization.

In [57]:
nlp = spacy.load("pt_core_news_lg")

df_sinop['tokens_spacy'] = df_sinop['sinopse'].apply(lambda x: [x.lemma_.lower() for x in nlp(x) if x.text.lower() not in stop and x.text.lower() not in pontuacoes])
df_sinop.loc[0,'tokens_spacy']

['história',
 'primeiro',
 'grande',
 'batalha',
 'fase',
 'americano',
 'guerra',
 'vietnã',
 'soldado',
 'ambos',
 'lado',
 'travar']

In [58]:
df_sinop = df_sinop[['titulo','sinopse','generos','tokens_spacy']]
df_sinop

,titulo,sinopse,generos,tokens_spacy
0,We Were Soldiers,A história da primeira grande batalha da fase ...,"['Ação', 'História', 'Guerra']","[história, primeiro, grande, batalha, fase, am..."
1,4Got10,"Um negócio de drogas dá errado, deixando corpo...","['Ação', 'Crime', 'Thriller']","[negócio, droga, dar, errar, deixar, corpo, xe..."
2,Pontypool,Quando o disc jockey Grant Mazzy se reporta à ...,"['Horror', 'Mistério', 'Ficção Científica']","[disc, jockey, grant, mazzy, reportar, estação..."
3,Ticker,Depois que o parceiro de um detetive de São Fr...,"['Ação', 'Crime', 'Thriller']","[parceiro, detetive, francisco, assassinar, te..."
4,Real Genius,Um adolescente prodígio tenso entra em uma fac...,"['Comédia', 'Romance', 'Ficção Científica']","[adolescente, prodígio, tenso, entrar, faculda..."
...,...,...,...,...
2995,JGM (JanaGanaMana),"É o próximo filme em 3 de agosto, anunciado po...","['Ação', 'Drama']","[próximo, filme, 3, agosto, anunciar, vijay, d..."
2996,The Shootist,Um pistoleiro moribundo passa seus últimos dia...,"['Drama', 'Romance', 'Ocidental']","[pistoleiro, moribundo, passar, último, dia, p..."
2997,Sleep Dealer,"Situado em um futuro próximo, mundo militariza...","['Drama', 'Ficção Científica', 'Thriller']","[situado, futuro, próximo, mundo, militarizar,..."
2998,Finding Neverland,Finding Neverland é um drama divertido sobre c...,['Drama'],"[finding, neverland, drama, divertido, sobre, ..."
2999,The Front Page,The Front Page é uma comédia do diretor Billy ...,['Comédia'],"[the, front, page, comédia, diretor, billy, wi..."

10 - Now, tokenize and clean the synopses. As a preliminary analysis, count the most frequently occurring tokens across all documents in the corpus.

In [59]:
import itertools
from collections import Counter

In [60]:
#da pra fazer com defaultdict
#sabem como funciona?
from collections import defaultdict
dic_total = defaultdict(int)
dic_total

#Qual a frequencia que os tokens aparecem em todos os documentos
#aqui considerando tokens que aparecem mais de uma vez em um mesmo documento
for document in df_sinop['tokens_spacy']:
    for token in document:
        dic_total[token]+=1

# dic_total
print(sorted(dic_total.items(), key=lambda item: item[1],reverse=True))

#or

full_list = Counter(list(itertools.chain(*df_sinop['tokens_spacy'])))
print(full_list.most_common())

[('vida', 522), ('ano', 369), ('jovem', 344), ('dois', 319), ('encontrar', 311), ('enquanto', 294), ('descobrir', 293), ('amigo', 276), ('dever', 267), ('poder', 266), ('homem', 264), ('fazer', 262), ('história', 256), ('família', 251), ('pai', 243), ('tornar', 240), ('todo', 240), ('novo', 236), ('cidade', 235), ('começar', 232), ('casa', 213), ('mundo', 211), ('tentar', 206), ('sobre', 198), ('filme', 194), ('grande', 186), ('filho', 185), ('levar', 183), ('guerra', 178), ('onde', 177), ('outro', 174), ('contra', 171), ('matar', 163), ('mulher', 162), ('conhecer', 161), ('lutar', 158), ('durante', 154), ('após', 152), ('ficar', 150), ('grupo', 150), ('assassino', 138), ('amor', 137), ('vez', 132), ('...', 131), ('próprio', 131), ('assassinato', 127), ('dia', 126), ('chamar', 126), ('ter', 124), ('morte', 124), ('terra', 122), ('filha', 121), ('tempo', 121), ('mãe', 121), ('policial', 120), ('tudo', 120), ('adolescente', 119), ('três', 118), ('irmão', 118), ('misterioso', 117), ('agente', 116), ('apenas', 115), ('americano', 114), ('agora', 114), ('deixar', 112), ('pessoa', 112), ('antes', 112), ('ver', 111), ('salvar', 111), ('bom', 109), ('decidir', 108), ('enfrentar', 108), ('chegar', 107), ('ir', 106), ('missão', 105), ('ajudar', 103), ('passar', 101), ('único', 101), ('logo', 100), ('viver', 99), ('acabar', 98), ('algum', 97), ('apaixonar', 97), ('mudar', 97), ('busca', 96), ('nova', 95), ('envolver', 92), ('pequeno', 92), ('local', 92), ('coisa', 92), ('trabalhar', 91), ('the', 91), ('equipe', 91), ('crime', 90), ('garota', 90), ('noite', 89), ('perder', 89), ('força', 88), ('seguir', 88), ('primeiro', 87), ('menino', 87), ('volta', 86), ('enviar', 86), ('série', 85), ('estranho', 83), ('velho', 83), ('usar', 82), ('procurar', 82), ('caminho', 82), ('criminoso', 81), ('roubar', 81), ('dar', 80), ('criança', 80), ('contar', 80), ('secreto', 80), ('york', 80), ('último', 80), ('dinheiro', 79), ('forçar', 79), ('relacionamento', 78), ('casal', 78), ('sequestrar', 77), ('gangue', 76), ('passado', 76), ('caso', 76), ('cada', 75), ('escapar', 74), ('conseguir', 74), ('trabalho', 73), ('transformar', 73), ('criar', 73), ('colocar', 73), ('voltar', 72), ('aventura', 71), ('receber', 70), ('antigo', 70), ('meio', 70), ('jogo', 69), ('problema', 69), ('casamento', 69), ('viajar', 68), ('ser', 68), ('cujo', 68), ('irmã', 67), ('ajuda', 67), ('futuro', 67), ('viagem', 67), ('humano', 67), ('entrar', 66), ('natal', 66), ('droga', 65), ('manter', 65), ('parecer', 65), ('prisão', 65), ('sair', 65), ('retornar', 65), ('querer', 65), ('investigar', 64), ('escola', 64), ('então', 64), ('perseguir', 64), ('junto', 64), ('descobrer', 64), ('mundial', 64), ('parte', 62), ('longo', 62), ('polícia', 62), ('ainda', 62), ('ação', 62), ('soldado', 61), ('detetive', 61), ('planejar', 61), ('mortal', 61), ('evento', 61), ('esposo', 61), ('verdadeiro', 61), ('verdade', 61), ('quatro', 60), ('romance', 60), ('morrer', 60), ('assassinar', 58), ('juntar', 58), ('luta', 58), ('vingança', 58), ('perceber', 57), ('próximo', 57), ('em este', 57), ('chefe', 57), ('segredo', 57), ('sobreviver', 57), ('final', 57), ('colega', 56), ('plano', 56), ('assumir', 56), ('sempre', 56), ('entanto', 56), ('fugir', 55), ('mal', 55), ('contratar', 55), ('carro', 55), ('saber', 55), ('marido', 55), ('coração', 55), ('real', 54), ('namorada', 54), ('recuperar', 54), ('sonho', 54), ('destruir', 53), ('estrela', 53), ('país', 53), ('medida', 53), ('inimigo', 53), ('trazer', 52), ('tomar', 52), ('corpo', 51), ('amizade', 51), ('perigoso', 51), ('sucesso', 51), ('ilha', 51), ('militar', 50), ('forma', 50), ('rico', 50), ('ganhar', 50), ('rua', 50), ('pouco', 50), ('ameaçar', 50), ('esposa', 50), ('batalha', 49), ('século', 49), ('embarcar', 49), ('poderoso', 49), ('sob', 49), ('britânico', 49), ('acontecer', 49), ('john', 49), ('acidente', 49), ('pegar', 49), ('unir', 48), ('arma', 47), ('desaparecer', 47), ('aprender', 47), ('ladrão', 47), ('cientista', 47), ('revelar', 47), ('bandido', 47), ('precisar', 47), ('década', 46), ('muito', 46), ('trás', 46), ('terror', 45), ('unidos', 45), ('médio', 45), ('liderar', 45), ('maneira', 44), ('exército', 44), ('destino', 44), ('belo', 44), ('lugar', 44), ('planeta', 44), ('esperar', 44), ('estados', 44), ('campo', 44), ('eua', 44), ('governo', 44), ('jornada', 43), ('proteger', 43), ('incluir', 43), ('cinco', 43), ('buscar', 43), ('deserto', 43), ('jack', 43), ('lado', 42), ('tentativa', 42), ('leia', 42), ('atrás', 42), ('esconder', 42), ('namorado', 42), ('negócio', 41), ('professor', 41), ('conto', 41), ('vários', 41), ('comédia', 41), ('londres', 41), ('ataque', 41), ('nunca', 41), ('dentro', 40), ('fim', 40), ('nenhum', 40), ('estudante', 40), ('cara', 40), ('morar', 40), ('arte', 40), ('oficial', 40), ('herói', 39), ('difícil', 39), ('lendário', 39), ('alto', 39), ('vítima', 39), ('piloto', 39), ('morto', 39), ('emprego', 39), ('esperança', 39), ('implacável', 39), ('verão', 38), ('resgatar', 38), ('algo', 38), ('cheio', 38), ('líder', 38), ('libertar', 38), ('nada', 38), ('vivo', 38), ('infância', 37), ('preso', 37), ('mágico', 37), ('alienígena', 37), ('baseado', 37), ('los', 37), ('angeles', 37), ('prender', 37), ('lidar', 37), ('quase', 37), ('famoso', 37), ('controle', 36), ('capturar', 36), ('corrupto', 36), ('rei', 36), ('acreditar', 36), ('nome', 36), ('ensino', 36), ('finalmente', 36), ('qualquer', 36), ('errar', 35), ('aluno', 35), ('especial', 35), ('diretor', 35), ('baixo', 35), ('realmente', 35), ('médico', 35), ('reunir', 35), ('sozinho', 35), ('américa', 35), ('dr.', 35), ('michael', 35), ('identidade', 35), ('sangue', 35), ('traficante', 34), ('pesadelo', 34), ('sombrio', 34), ('amante', 34), ('estrada', 34), ('personagem', 34), ('james', 34), ('memória', 34), ('apresentar', 34), ('veterano', 34), ('violento', 34), ('sobrevivente', 34), ('vir', 34), ('impedir', 34), ('terrorista', 33), ('jogar', 33), ('acidentalmente', 33), ('corrida', 33), ('pessoal', 33), ('se', 33), ('caçador', 33), ('criatura', 33), ('guerreiro', 33), ('medo', 33), ('atrair', 33), ('lei', 33), ('segunda', 33), ('treinar', 33), ('vingar', 33), ('parceiro', 32), ('perfeito', 32), ('advogado', 32), ('carreira', 32), ('semana', 32), ('embora', 32), ('distante', 32), ('selvagem', 32), ('lá', 32), ('aceitar', 32), ('hora', 32), ('através', 32), ('diferente', 32), ('pedir', 32), ('abandonar', 32), ('assim', 31), ('desde', 31), ('atacar', 31), ('negro', 31), ('preparar', 31), ('chance', 31), ('serviço', 31), ('correr', 31), ('casar', 31), ('solitário', 31), ('tripulação', 31), ('remoto', 31), ('capitão', 31), ('lançar', 30), ('acusar', 30), ('cinema', 30), ('visitar', 30), ('membro', 30), ('desenvolver', 30), ('fbi', 30), ('amar', 30), ('mistério', 30), ('floresta', 30), ('terrível', 30), ('encontro', 30), ('abrir', 30), ('empresa', 30), ('programa', 30), ('humanidade', 30), ('solteiro', 30), ('marcial', 30), ('zumbi', 29), ('continuar', 29), ('gângster', 29), ('rock', 29), ('tom', 29), ('companheiro', 29), ('show', 29), ('mesmo', 29), ('dirigir', 29), ('david', 29), ('banco', 29), ('realidade', 29), ('início', 29), ('cair', 29), ('olhar', 29), ('político', 29), ('segurança', 28), ('presidente', 28), ('caçar', 28), ('música', 28), ('empresário', 28), ('dizer', 28), ('internacional', 28), ('resgate', 28), ('tornar se', 28), ('basear', 28), ('conspiração', 28), ('aparentemente', 28), ('realizar', 28), ('partir', 28), ('evitar', 28), ('bem', 28), ('mestre', 28), ('resolver', 28), ('improvável', 27), ('norte', 27), ('classe', 27), ('cabeça', 27), ('paris', 27), ('aterrorizar', 27), ('ameaça', 27), ('frank', 27), ('oferecer', 27), ('sexual', 27), ('alvo', 27), ('amiga', 27), ('killer', 27), ('sul', 27), ('máfia', 27), ('garoto', 27), ('califórnia', 27), ('causar', 26), ('ator', 26), ('férias', 26), ('documentário', 26), ('experiência', 26), ('iniciar', 26), ('organização', 26), ('fuga', 26), ('vampiro', 26), ('mau', 26), ('príncipe', 26), ('social', 26), ('tão', 26), ('comum', 26), ('sistema', 26), ('confrontar', 26), ('gêmeo', 26), ('papel', 26), ('malvado', 26), ('particular', 26), ('mão', 26), ('cuidar', 26), ('presente', 26), ('menina', 26), ('espírito', 26), ('sam', 26), ('faculdade', 25), ('espacial', 25), ('suspeito', 25), ('recrutar', 25), ('derrubar', 25), ('festa', 25), ('cia', 25), ('reino', 25), ('gato', 25), ('interpretar', 25), ('serial', 25), ('parar', 25), ('mar', 25), ('formar', 25), ('determinar', 25), ('bando', 25), ('rainha', 25), ('quarto', 24), ('convencer', 24), ('recusar', 24), ('rival', 24), ('clássico', 24), ('aparecer', 24), ('importante', 24), ('épico', 24), ('decisão', 24), ('inspirar', 24), ('provar', 24), ('pagar', 24), ('novamente', 24), ('risco', 24), ('sociedade', 24), ('amoroso', 24), ('popular', 24), ('ouro', 24), ('time', 24), ('princesa', 24), ('sete', 24), ('george', 24), ('trama', 24), ('perigo', 24), ('artista', 24), ('adulto', 24), ('escolher', 24), ('espaço', 23), ('bebê', 23), ('roubo', 23), ('terminar', 23), ('separar', 23), ('livro', 23), ('fronteira', 23), ('apartamento', 23), ('habilidade', 23), ('estilo', 23), ('elite', 23), ('acordar', 23), ('sinistro', 23), ('assalto', 23), ('paz', 23), ('richard', 23), ('sr.', 23), ('desconhecer', 23), ('concordar', 23), ('jason', 23), ('superar', 23), ('hollywood', 23), ('sofrer', 23), ('monstro', 23), ('noiva', 23), ('motorista', 23), ('romântico', 23), ('feliz', 23), ('rápido', 23), ('peter', 23), ('violência', 23), ('civil', 23), ('navio', 23), ('seguro', 23), ('resto', 23), ('jornalista', 23), ('excêntrico', 22), ('versão', 22), ('lua', 22), ('notório', 22), ('disfarçar', 22), ('virar', 22), ('geração', 22), ('fada', 22), ('mike', 22), ('defender', 22), ('rapidamente', 22), ('derrotar', 22), ('bruxa', 22), ('momento', 22), ('casado', 22), ('visão', 22), ('atingir', 22), ('brilhante', 22), ('vizinho', 22), ('oeste', 22), ('cometer', 22), ('compartilhar', 22), ('louco', 22), ('prestes', 22), ('pois', 22), ('entregar', 21), ('hospital', 21), ('mercenário', 21), ('deparar', 21), ('branco', 21), ('obter', 21), ('primeira', 21), ('dono', 21), ('doença', 21), ('consequência', 21), ('thriller', 21), ('seis', 21), ('china', 21), ('maligno', 21), ('desejo', 21), ('vencer', 21), ('recentemente', 21), ('fantasia', 21), ('tarde', 21), ('centrar', 21), ('tecnologia', 21), ('garantir', 21), ('condenar', 21), ('responsável', 21), ('sequência', 21), ('escrever', 21), ('fazendeiro', 21), ('destruição', 21), ('ambos', 20), ('xerife', 20), ('mexicano', 20), ('refém', 20), ('deus', 20), ('cumprir', 20), ('russo', 20), ('quanto', 20), ('sobrenatural', 20), ('conta', 20), ('loja', 20), ('participar', 20), ('drama', 20), ('animal', 20), ('várias', 20), ('rastrear', 20), ('tv', 20), ('construir', 20), ('general', 20), ('unidade', 20), ('fechar', 20), ('jim', 20), ('olho', 20), ('jogador', 20), ('testemunha', 20), ('esforço', 20), ('banda', 20), ('jones', 20), ('milhão', 20), ('familiar', 20), ('segundo', 20), ('trabalhador', 20), ('fantasma', 20), ('nave', 20), ('inocente', 20), ('escritor', 20), ('aspirante', 20), ('inglaterra', 20), ('avião', 20), ('caos', 20), ('fazenda', 20), ('justiça', 19), ('desafio', 19), ('prisioneiro', 19), ('interior', 19), ('lenda', 19), ('comprar', 19), ('nascer', 19), ('estado', 19), ('horrível', 19), ('tio', 19), ("'s", 19), ('universo', 19), ('isolar', 19), ('estrelar', 19), ('harry', 19), ('centro', 19), ('afetar', 19), ('repórter', 19), ('musical', 19), ('entrevista', 19), ('falar', 19), ('par', 19), ('aproximar', 19), ('crescer', 19), ('músico', 19), ('charles', 19), ('alguém', 19), ('inesperado', 19), ('público', 19), ('mostrar', 19), ('nazista', 19), ('ascensão', 19), ('projeto', 18), ('ninguém', 18), ('paciente', 18), ('principal', 18), ('funcionário', 18), ('max', 18), ('experimento', 18), ('brutal', 18), ('universitário', 18), ('lindo', 18), ('anterior', 18), ('competir', 18), ('aumentar', 18), ('armar', 18), ('guarda', 18), ('inteligência', 18), ('operação', 18), ('transportar', 18), ('envolvir', 18), ('queda', 18), ('problemático', 18), ('ato', 18), ('vilão', 18), ('vegas', 18), ('liberdade', 18), ('clube', 18), ('conquistar', 18), ('emocionante', 18), ('nuclear', 18), ('caber', 18), ('frança', 18), ('invasão', 18), ('senhor', 18), ('nick', 18), ('invadir', 18), ('lee', 18), ('vietnã', 17), ('pensar', 17), ('of', 17), ('bizarro', 17), ('totalmente', 17), ('hotel', 17), ('sobrevivência', 17), ('alice', 17), ('redor', 17), ('obscuro', 17), ('favorito', 17), ('designar', 17), ('visita', 17), ('oito', 17), ('desesperar', 17), ('robert', 17), ('computador', 17), ('área', 17), ('questão', 17), ('imaginar', 17), ('rebelde', 17), ('situado', 17), ('vila', 17), ('autoridade', 17), ('desafiar', 17), ('adotar', 17), ('situação', 17), ('quebrar', 17), ('fugitivo', 17), ('traição', 17), ('administrar', 17), ('erro', 17), ('ex-presidiário', 17), ('longe', 17), ('tragédia', 17), ('profissional', 17), ('francês', 17), ('las', 17), ('talentoso', 17), ('noel', 17), ('paixão', 17), ('méxico', 17), ('porque', 17), ('adotivo', 17), ('bob', 17), ('de esse', 17), ('povo', 17), ('tirar', 17), ('vínculo', 17), ('mudança', 17), ('convidar', 17), ('desaparecimento', 17), ('acampamento', 17), ('controlar', 17), ('extraordinário', 17), ('ordem', 17), ('permanecer', 17), ('gostar', 17), ('enganar', 16), ('crise', 16), ('comunidade', 16), ('testemunhar', 16), ('vigilante', 16), ('submundo', 16), ('complexo', 16), ('repente', 16), ('caça', 16), ('duplo', 16), ('mansão', 16), ('devido', 16), ('normal', 16), ('pista', 16), ('pobre', 16), ('máquina', 16), ('descoberta', 16), ('selva', 16), ('inocência', 16), ('montanha', 16), ('magnata', 16), ('sorte', 16), ('prostituta', 16), ('forte', 16), ('marcar', 16), ('cruzar', 16), ('veer', 16), ('kevin', 16), ('bairro', 16), ('papai', 16), ('passeio', 16), ('fred', 16), ('cena', 16), ('cantora', 16), ('frustrar', 16), ('paul', 16), ('futebol', 16), ('moderno', 16), ('desonesto', 16), ('aéreo', 16), ('sexo', 16), ('vender', 16), ('dragão', 16), ('perspectiva', 16), ('robô', 16), ('féria', 16), ('surgir', 16), ('talento', 16), ('tarefa', 16), ('demônio', 16), ('propriedade', 16), ('conselho', 16), ('estação', 15), ('rádio', 15), ('francisco', 15), ('sentir', 15), ('aliado', 15), ('danny', 15), ('torno', 15), ('astuto', 15), ('morador', 15), ('palavra', 15), ('texas', 15), ('vigarista', 15), ('viúva', 15), ('rumo', 15), ('torneio', 15), ('recompensa', 15), ('12', 15), ('cachorro', 15), ('linha', 15), ('inglês', 15), ('mês', 15), ('filmar', 15), ('mergulhar', 15), ('limite', 15), ('órfão', 15), ('desencadeiar', 15), ('mentor', 15), ('agência', 15), ('cruel', 15), ('científico', 15), ('causa', 15), ('movimento', 15), ('perda', 15), ('heroína', 15), ('joe', 15), ('exigir', 15), ('2', 15), ('eliminar', 15), ('atual', 15), ('indiano', 15), ('bonito', 15), ('mafioso', 15), ('arriscar', 15), ('possível', 15), ('evidência', 15), ('japonês', 15), ('voar', 15), ('existir', 15), ('inferno', 15), ('mente', 15), ('suspeitar', 15), ('pacífico', 15), ('acompanhar', 15), ('intenção', 15), ('demais', 15), ('navegar', 15), ('decadente', 15), ('billy', 15), ('van', 15), ('vírus', 14), ('suicídio', 14), ('pós-apocalíptico', 14), ('presa', 14), ('personalidade', 14), ('dedicar', 14), ('horror', 14), ('amado', 14), ('inesperadamente', 14), ('sarah', 14), ('cão', 14), ('comando', 14), ('gigante', 14), ('lutador', 14), ('atormentar', 14), ('steve', 14), ('além', 14), ('alex', 14), ('prova', 14), ('scott', 14), ('biológico', 14), ('irlandês', 14), ('austrália', 14), ('ocorrer', 14), ('europa', 14), ('vontade', 14), ('academia', 14), ('assombrar', 14), ('atividade', 14), ('processo', 14), ('investigação', 14), ('raça', 14), ('índia', 14), ('oportunidade', 14), ('cultura', 14), ('treinamento', 14), ('resposta', 14), ('itália', 14), ('1980', 14), ('alma', 14), ('felicidade', 14), ('jimmy', 14), ('cantor', 14), ('considerar', 14), ('arthur', 14), ('inteligente', 14), ('comportamento', 14), ('tesouro', 14), ('claro', 14), ('teste', 14), ('complicado', 14), ('atrapalhar', 14), ('chicago', 14), ('menos', 14), ('especialista', 14), ('modelo', 14), ('base', 14), ('perto', 14), ('testar', 14), ('resultado', 14), ('terceiro', 14), ('trágico', 14), ('beira', 14), ('bordo', 14), ('existência', 14), ('direito', 14), ('baile', 14), ('carregar', 14), ('elizabeth', 14), ('20', 14), ('figura', 14), ('aterrorizante', 14), ('ferir', 13), ('cego', 13), ('apesar', 13), ('informar', 13), ('impiedoso', 13), ('sádico', 13), ('lista', 13), ('profundo', 13), ('data', 13), ('uner', 13), ('idade', 13), ('charlie', 13), ('feminino', 13), ('televisão', 13), ('exatamente', 13), ('jackson', 13), ('conectar', 13), ('produtor', 13), ('perturbar', 13), ('city', 13), ('combinar', 13), ('dez', 13), ('conexão', 13), ('involuntariamente', 13), ('espião', 13), ('trair', 13), ('ensinar', 13), ('ambicioso', 13), ('árvore', 13), ('áfrica', 13), ('original', 13), ('tenente', 13), ('secretamente', 13), ('achar', 13), ('carta', 13), ('ideia', 13), ('emoção', 13), ('jurar', 13), ('gênio', 13), ('jay', 13), ('espalhar', 13), ('determinado', 13), ('johnson', 13), ('italiano', 13), ('encarregar', 13), ('bar', 13), ('relação', 13), ('noivo', 13), ('campeão', 13), ('17', 13), ('garra', 13), ('vídeo', 13), ('desistir', 13), ('dificuldade', 13), ('assistente', 13), ('vencedor', 13), ('criação', 13), ('proteção', 13), ('beisebol', 13), ('diversão', 13), ('10', 13), ('kelly', 13), ('fotógrafo', 13), ('origem', 13), ('completar', 13), ('companhia', 13), ('sobrinho', 13), ('batman', 12), ('vinte', 12), ('jane', 12), ('fonte', 12), ('tanto', 12), ('expedição', 12), ('habitante', 12), ('manhattan', 12), ('efeito', 12), ('lembrar', 12), ('namorar', 12), ('psiquiatra', 12), ('coleção', 12), ('apaixonado', 12), ('experimentar', 12), ('tensão', 12), ('desejar', 12), ('misteriosamente', 12), ('dor', 12), ('pronto', 12), ('desmoronar', 12), ('vermelho', 12), ('lobo', 12), ('sequestro', 12), ('nacional', 12), ('ilegal', 12), ('aldeia', 12), ('bond', 12), ('ficção', 12), ('animar', 12), ('avançar', 12), ('naval', 12), ('bill', 12), ('flashback', 12), ('mídia', 12), ('henry', 12), ('mulherengo', 12), ('experiente', 12), ('desajustar', 12), ('arrastar', 12), ('indústria', 12), ('em ele', 12), ('dívida', 12), ('19', 12), ('lentamente', 12), ('conflito', 12), ('afeganistão', 12), ('afirmar', 12), ('confronto', 12), ('longa-metragem', 12), ('desesperadamente', 12), ('trocar', 12), ('enorme', 12), ('mutante', 12), ('sentimento', 12), ('feiticeiro', 12), ('divorciar', 12), ('pesquisa', 12), ('peça', 12), ('rivalidade', 12), ('incomum', 12), ('ford', 12), ('ingênuo', 12), ('esquema', 12), ('completo', 12), ('tratar', 12), ('aposentado', 12), ('convidado', 12), ('época', 12), ('oscar', 12), ('fortuna', 12), ('lar', 12), ('narrar', 12), ('dominar', 12), ('moda', 12), ('desencadear', 12), ('fracassar', 12), ('sangrento', 12), ('soviético', 12), ('prédio', 12), ('oposto', 12), ('fama', 12), ('diamante', 12), ('dinossauro', 12), ('submarino', 12), ('relato', 11), ('pretender', 11), ('superman', 11), ('restaurante', 11), ('examinar', 11), ('11', 11), ('pousar', 11), ('voz', 11), ('chegada', 11), ('hilário', 11), ('turma', 11), ('permitir', 11), ('18', 11), ('ponto', 11), ('alemão', 11), ('adaptação', 11), ('fé', 11), ('cineasta', 11), ('conjunto', 11), ('rato', 11), ('auge', 11), ('imigrante', 11), ('eventualmente', 11), ('relutantemente', 11), ('seguinte', 11), ('de isso', 11), ('high', 11), ('duro', 11), ('expor', 11), ('motivo', 11), ('daniel', 11), ('chris', 11), ('aérea', 11), ('animação', 11), ('inteiro', 11), ('julgamento', 11), ('ligar', 11), ('físico', 11), ('explora', 11), ('posse', 11), ('estabelecer', 11), ('contato', 11), ('falecido', 11), ('legado', 11), ('má', 11), ('certo', 11), ('ambientar', 11), ('dividir', 11), ('véspera', 11), ('sargento', 11), ('andy', 11), ('atriz', 11), ('centena', 11), ('natureza', 11), ('30', 11), ('14', 11), ('informação', 11), ('videogame', 11), ('quadrilha', 11), ('interesse', 11), ('tubarã

11 - Analyzing the most frequently used words, do you think there are any that should have been considered stopwords? Which ones? How would you suggest expanding the list of stopwords?

In [63]:
len(df_sinop)

3000

12 - We now have our tokenized and cleaned data. It is important to determine the total number of unique tokens across the entire corpus and identify which tokens are present in each document. Therefore, create a matrix where each row represents one of the 3,000 tokenized documents and each column represents a unique token. Count how many times each token appears in each document and fill in the matrix accordingly.

In [61]:
#lista para criar um dataframe com os vetores BoW
list_dict_documents = []

#para cada documento
for document in df_sinop['tokens_spacy']:
    #cria-se um dicionado default
    cont_doc = Counter(document)
    dict_doc = defaultdict(int)
    for key in dic_total.keys():
        if key in cont_doc.keys():
            #faz uma soma
            dict_doc[key] = cont_doc[key]
        else:
            dict_doc[key] = 0

    #adiciona ao final do looping a linha referente ao documento
    list_dict_documents.append(dict_doc)

In [64]:
import pandas as pd

#criando o dataframe
df_cont = pd.DataFrame(list_dict_documents)
df_cont

,história,primeiro,grande,batalha,fase,americano,guerra,vietnã,soldado,ambos,...,neverland,pan,escrita,j.m.,barrie,sylvia,wilder,lemmon,matthau,esgotado
0,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2998,1,0,0,0,0,0,0,0,0,0,...,2,2,1,1,2,1,0,0,0,0
2999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1

In [65]:
df_cont['vida'].sum()

np.int64(522)

In [66]:
dic_total['vida']

522

13 - What uses do you suggest we explore with the above dataframe?

In [30]:
#each line is a document
#each column is a token

14 - How can we interpret the columns of the dataframe? Is it possible to compare the context of two documents using rows vectors?

In [31]:
#we can compare documents based on if they share same tokens

15 - Consider the formula:

$$
TF(t) = \frac{\text{Number of times the term } t \text{ appears in the document}}{\text{Total number of terms in the document}}
$$

Use the dataframe created in exercise 10 to now create a dataframe that, instead of the count of a specific token in a given document, presents its TF.

In [72]:
list_dict_documents[0]

defaultdict(int,
            {'história': 1,
             'primeiro': 1,
             'grande': 1,
             'batalha': 1,
             'fase': 1,
             'americano': 1,
             'guerra': 1,
             'vietnã': 1,
             'soldado': 1,
             'ambos': 1,
             'lado': 1,
             'travar': 1,
             'negócio': 0,
             'droga': 0,
             'dar': 0,
             'errar': 0,
             'deixar': 0,
             'corpo': 0,
             'xerife': 0,
             'atirar': 0,
             'vice': 0,
             'dinheiro': 0,
             'amnésico': 0,
             'ferir': 0,
             'fugir': 0,
             '3.000.000': 0,
             'dea': 0,
             'investigar': 0,
             'assim': 0,
             'traficante': 0,
             'pai': 0,
             'deputado': 0,
             'matar': 0,
             'disc': 0,
             'jockey': 0,
             'grant': 0,
             'mazzy': 0,
             'reportar': 0,
             'estação': 0,
             'rádio': 0,
             'porão': 0,
             'cidade': 0,
             'canadense': 0,
             'pontypool': 0,
             'pensar': 0,
             'apenas': 0,
             'dia': 0,
             'trabalho': 0,
             'ouver': 0,
             'relato': 0,
             'vírus': 0,
             'transformar': 0,
             'pessoa': 0,
             'zumbi': 0,
             'barricar': 0,
             'cabine': 0,
             'tentar': 0,
             'descobrir': 0,
             'maneira': 0,
             'alertar': 0,
             'ouvinte': 0,
             'sobre': 0,
             'improvável': 0,
             'modo': 0,
             'transmissão': 0,
             'parceiro': 0,
             'detetive': 0,
             'francisco': 0,
             'assassinar': 0,
             'terrorista': 0,
             'irlanda': 0,
             'norte': 0,
             'policial': 0,
             'juntar': 0,
             'esquadrão': 0,
             'antibombar': 0,
             'levá-los': 0,
             'justiça': 0,
             'adolescente': 0,
             'prodígio': 0,
             'tenso': 0,
             'entrar': 0,
             'faculdade': 0,
             'engenharia': 0,
             'ponta': 0,
             'sentir': 0,
             'estranho': 0,
             'aluno': 0,
             'despreocupar': 0,
             'professor': 0,
             'pretender': 0,
             'projeto': 0,
             'laser': 0,
             'arma': 0,
             'militar': 0,
             'excêntrico': 0,
             'colega': 0,
             'quarto': 0,
             'planejar': 0,
             'arruinar': 0,
             'plano': 0,
             'terra': 0,
             'alternativa': 0,
             'coringa': 0,
             'enganar': 0,
             'superman': 0,
             'lois': 0,
             'lane': 0,
             'causar': 0,
             'agitação': 0,
             'herói': 0,
             'decidir': 0,
             'assumir': 0,
             'controle': 0,
             'batman': 0,
             'aliado': 0,
             'detê-lo': 0,
             'tim': 0,
             'robbins': 0,
             'chamar': 0,
             'trabalhar': 0,
             'dois': 0,
             'menino': 0,
             'walter': 0,
             'josh': 0,
             'hutcherson': 0,
             'danny': 0,
             'jonah': 0,
             'bobo': 0,
             'cuidado': 0,
             'irmã': 0,
             'lisa': 0,
             'kristen': 0,
             'stewart': 0,
             'dever': 0,
             'ficar': 0,
             'dentro': 0,
             'casa': 0,
             'antecipar': 0,
             'chato': 0,
             'chocado': 0,
             'começar': 0,
             'jogar': 0,
             'zathura': 0,
             'jogo': 0,
             'tabuleiro': 0,
             'tema': 0,
             'espacial': 0,
             'perceber': 0,
             'ter': 0,
             'poder': 0,
             'místico': 0,
             'lançar': 0,
             'espaço': 0,
             'ajuda': 0,
             'astronauta': 0,
             'dax': 0,
             'shepard': 0,
             'voltar': 0,
             'após': 0,
             'colapso': 0,
             'nervoso': 0,
             'tentativa': 0,
             'suicídio': 0,
             'ator': 0,
             'envelhecido': 0,
             'envolver': 0,
             'mulher': 0,
             'jovem': 0,
             'logo': 0,
             'difícil': 0,
             'acompanhar ela': 0,
             'dan': 0,
             'kristi': 0,
             'boas-vinda': 0,
             'bebê': 0,
             'recém-nascido': 0,
             'presença': 0,
             'demoníaco': 0,
             'aterrorizá lós': 0,
             'destruir': 0,
             'mundo': 0,
             'perfeito': 0,
             'transformar ele': 0,
             'pesadelo': 0,
             'inevitável': 0,
             'câmera': 0,
             'segurança': 0,
             'capturar': 0,
             'tormento': 0,
             'tornar': 0,
             'cada': 0,
             'minuto': 0,
             'terrivelmente': 0,
             'real': 0,
             'três': 0,
             'trapalhão': 0,
             'reservista': 0,
             'exército': 0,
             'destino': 0,
             'iraque': 0,
             'acidentalmente': 0,
             'vilarejo': 0,
             'mexicano': 0,
             'sitiar': 0,
             'força': 0,
             'hostil': 0,
             'giro': 0,
             'torno': 0,
             'cego': 0,
             'mohammed': 0,
             'liberar': 0,
             'escola': 0,
             'especial': 0,
             'teerã': 0,
             'férias': 0,
             'verão': 0,
             'envergonhar': 0,
             'oprimido': 0,
             'cegueira': 0,
             'chegar': 0,
             'atrasado': 0,
             'buscar ele': 0,
             'convencer': 0,
             'diretor': 0,
             'durante': 0,
             'recusar': 0,
             'então': 0,
             'acabar': 0,
             'levar ele': 0,
             'futuro': 0,
             'pós-apocalíptico': 0,
             'gangue': 0,
             'rival': 0,
             'lutar': 0,
             'frazier': 0,
             'park': 0,
             'beat': 0,
             'revelation': 0,
             'versão': 0,
             'mortal': 0,
             'dance': 0,
             'revolution(tm': 0,
             'criminoso': 0,
             'inexperiente': 0,
             'ben': 0,
             'assaltar': 0,
             'restaurante': 0,
             'pequeno': 0,
             'roubo': 0,
             'mal': 0,
             'crise': 0,
             'refém': 0,
             'presa': 0,
             'namorada': 0,
             'empresária': 0,
             'adie': 0,
             'graham': 0,
             'sociopata': 0,
             'astuto': 0,
             'comunidade': 0,
             'sombrio': 0,
             'temente': 0,
             'deus': 0,
             'abalar': 0,
             'assassinato': 0,
             'criança': 0,
             'psicóloga': 0,
             'examinar': 0,
             'dorothy': 0,
             'mills': 0,
             'acusar': 0,
             'crime': 0,
             'apesar': 0,
             'resistência': 0,
             'morador': 0,
             'terapeuta': 0,
             'suspeito': 0,
             'sofra': 0,
             'transtorno': 0,
             'personalidade': 0,
             'múltiplo': 0,
             '...': 0,
             'julho': 0,
             '1969': 0,
             'corrida': 0,
             'terminar': 0,
             'apollo': 0,
             '11': 0,
             'cumprir': 0,
             'desafio': 0,
             'presidente': 0,
             'kennedy': 0,
             '“': 0,
             'pousar': 0,
             'homem': 0,
             'lua': 0,
             'trazê-lo': 0,
             'volta': 0,
             'salvo': 0,
             '”': 0,
             'ninguém': 0,
             'testemunhar': 0,
             'pouso': 0,
             'lunar': 0,
             'jamais': 0,
             'esquecer': 0,
             'documentário': 0,
             'al': 0,
             'reinert': 0,
             'all': 0,
             'mankind': 0,
             'vinte': 0,
             'quatro': 0,
             'viajar': 0,
             'contar': 0,
             'palavra': 0,
             'voz': 0,
             'usar': 0,
             'imagem': 0,
             'experiência': 0,
             'quarenta': 0,
             'ano': 0,
             'continuar': 0,
             'ser': 0,
             'obra': 0,
             'cinema': 0,
             'radical': 0,
             'visualmente': 0,
             'deslumbrante': 0,
             'fazer': 0,
             'evento': 0,
             'costeiro': 0,
             'russo': 0,
             'kolya': 0,
             'forçar': 0,
             'contra': 0,
             'prefeito': 0,
             'corrupto': 0,
             'informar': 0,
             'demoler': 0,
             'recrutar': 0,
             'amigo': 0,
             'advogado': 0,
             'ajudar': 0,
             'chegada': 0,
             'trazer': 0,
             'infortúnio': 0,
             'família': 0,
             'clássico': 0,
             'romance': 0,
             'jane': 0,
             'austen': 0,
             'preconceito': 0,
             'ocorrir': 0,
             'classe': 0,
             'século': 0,
             'xix': 0,
             'orgulho': 0,
             'separar': 0,
             'amante': 0,
             'abusar': 0,
             'mentalmente': 0,
             'escravizar': 0,
             'coager': 0,
             'prostituição': 0,
             'impiedoso': 0,
             'morrer': 0,
             'missão': 0,
             'diretamente': 0,
             'espancar': 0,
             'pecador': 0,
             'santa': 0,
             'estritamente': 0,
             'pessoal': 0,
             'prisioneiro': 0,
             'vigilante': 0,
             'notório': 0,
             'gângster': 0,
             'pat': 0,
             'tate': 0,
             'sobir': 0,
             'hierarquia': 0,
             'submundo': 0,
             'essex': 0,
             'prequela': 0,
             'franquia': 0,
             'rise': 0,
             'of': 0,
             'the': 0,
             'footsoldier': 0,
             'casai': 0,
             'interior': 0,
             'texas': 0,
             'busca': 0,
             'lenda': 0,
             'urbano': 0,
             'bizarro': 0,
             'sádico': 0,
             'assassino': 0,
             'série': 0,
             'perseguição': 0,
             'caçar': 0,
             'temido': 0,
             'próprio': 0,
             'agenda': 0,
             'secreto': 0,
             'vida': 0,
             'ícone': 0,
             'música': 0,
             'elvis': 0,
             'presley': 0,
             'desde': 0,
             'infância': 0,
             'estrela': 0,
             'rock': 0,
             'década': 0,
             '1950': 0,
             'manter': 0,
             'relacionamento': 0,
             'complexo': 0,
             'empresário': 0,
             'coronel': 0,
             'tom': 0,
             'parker': 0,
             'paciente': 0,
             'câncer': 0,
             'iniciar': 0,
             'jornada': 0,
             'afirmação': 0,
             'visitar': 0,
             'autor': 0,
             'recluso': 0,
             'amsterdã': 0,
             'solteira': 0,
             'meia-idade': 0,
             'belo': 0,
             'irene': 0,
             'margarita': 0,
             'buy': 0,
             'totalmente': 0,
             'dedicar': 0,
             'inspetora': 0,
             'hotel': 0,
             'luxo': 0,
             'constantemente': 0,
             'estrada': 0,
             'entregar': 0,
             'prazer': 0,
             'caro': 0,
             'resort': 0,
             'impecável': 0,
             'sempre': 0,
             'incógnita': 0,
             'sozinha': 0,
             'escapar': 0,
             'próximo': 0,
             'exótico': 0,
             'lista': 0,
             'verificação': 0,
             'laptop': 0,
             'reboque': 0,
             'bom': 0,
             'ex': 0,
             'andrea': 0,
             'stefano': 0,
             'accorsi': 0,
             'fonte': 0,
             'apoio': 0,
             'emocional': 0,
             'repente': 0,
             'indisponível': 0,
             'profundo': 0,
             'existencial': 0,
             'forma': 0,
             'engano': 0,
             'dizer': 0,
             'companheiro': 0,
             'viagem': 0,
             'névoa': 0,
             'sauna': 0,
             'vapor': 0,
             'significado': 0,
             'disfarçar': 0,
             'derrubar': 0,
             'organização': 0,
             'parte': 0,
             'minissérie': 0,
             'dinamarquês': 0,
             'editar': 0,
             'filme': 0,
             'riget': 0,
             'passar': 0,
             'ala': 0,
             'neurocirúrgico': 0,
             'rigshospitalet': 0,
             'copenhague': 0,
             'principal': 0,
             'hospital': 0,
             'país': 0,
             'apelidar': 0,
             'show': 0,
             'seguir': 0,
             'personagem': 0,
             'tanto': 0,
             'funcionário': 0,
             'quanto': 0,
             'enquanto': 0,
             'encontrar': 0,
             'fenômeno': 0,
             'humano': 0,
             'sobrenatural': 0,
             'aparecer': 0,
             'estimar': 0,
             'livro': 0,
             '1001': 0,
             'ver': 0,
             'antes': 0,
             'fronteira': 0,
             'expedição': 0,
             'comércio': 0,
             'pele': 0,
             '1820': 0,
             'luta': 0,
             'sobrevivência': 0,
             'atacar': 0,
             'urso': 0,
             'membro': 0,
             'equipe': 0,
             'caça': 0,
             'tyler': 0,
             'rake': 0,
             'destemido': 0,
             'mercenário': 0,
             'mercado': 0,
             'negro': 0,
             'embarcar': 0,
             'extração': 0,
             'carreira': 0,
             'alistar': 0,
             'resgatar': 0,
             'filho': 0,
             'sequestrar': 0,
             'internacional': 0,
             'preso': 0,
             'vigarista': 0,
             'rural': 0,
             'desertor': 0,
             'habitante': 0,
             'garota': 0,
             'rico': 0,
             'proteger': 0,
             'dupla': 0,
             'fuga': 0,
             'ira': 0,
             'perseguir': 0,
             'todo': 0,
             'viúva': 0,
             'filha': 0,
             'outro': 0,
             'preparar': 0,
             'tudo': 0,
             'novo': 0,
             'alice': 0,
             'palmer': 0,
             '16': 0,
             'afogar': 0,
             'represa': 0,
             'local': 0,
             'recuperar': 0,
             'enlutar': 0,
             'enterra': 0,
             'inexplicável': 0,
             '\u200b\u200bcentrar': 0,
             'redor': 0,
             'inquietos': 0,
             'palmers': 0,
             'procurar': 0,
             'médium': 0,
             'parapsicólogo': 0,
             'ray': 0,
             'kemeny': 0,
             'levar': 0,
             'duplo': 0,
             'lago': 0,
             'mungo': 0,
             'passado': 0,
             'emerger': 0,
             'despejar': 0,
             'apartamento': 0,
             'manhattan': 0,
             'casal': 0,
             'comprar': 0,
             'parecer': 0,
             'sonho': 0,
             'sobrecarregado': 0,
             'esvaziamento': 0,
             'conta': 0,
             'bancário': 0,
             'lutando': 0,
             'junto': 0,
             'mansão': 0,
             'desconexar': 0,
             'desmorona': 0,
             'assistir': 0,
             'horror': 0,
             'hilário': 0,
             'incluir': 0,
             'pia': 0,
             'cozinha': 0,
             'desaparecer': 0,
             'poço': 0,
             'longo': 0,
             'data': 0,
             'will': 0,
             'bryan': 0,
             'matt': 0,
             'corey': 0,
             'amado': 0,
             'avô': 0,
             'inesperadamente': 0,
             'reivindicar': 0,
             'herança': 0,
             'turma': 0,
             'conhecer': 0,
             'prima': 0,
             'jessie': 0,
             'hilariante': 0,
             'ler': 0,
             'virar': 0,
             'cabeça': 0,
             'baixo': 0,
             'esposo': 0,
             'max': 0,
             'simkin': 0,
             'consertar': 0,
             'sapato': 0,
             'mesmo': 0,
             'loja': 0,
             'nova': 0,
             'york': 0,
             'geração': 0,
             'desiludido': 0,
             'rotina': 0,
             'diário': 0,
             'deparar': 0,
             'mágico': 0,
             'permitir': 0,
             'cliente': 0,
             'vez': 0,
             'colocar se': 0,
             'lugar': 0,
             'único': 0,
             'realmente': 0,
             'participar': 0,
             'poderoso': 0,
             'experimento': 0,
             'médico': 0,
             'ganhar': 0,
             'habilidade': 0,
             'telepático': 0,
             'pirocinético': 0,
             'exploração': 0,
             'nação': 0,
             'tecnologicamente': 0,
             'desenvolvimento': 0,
             'efeito': 0,
             'transição': 0,
             'modernização': 0,
             'estilo': 0,
             'ocidental': 0,
             'jean-baptiste': 0,
             'grenouille': 0,
             'nascer': 0,
             'fedor': 0,
             'paris': 0,
             '18': 0,
             'desenvolver': 0,
             'sentido': 0,
             'olfativo': 0,
             'superior': 0,
             'criar': 0,
             'perfume': 0,
             'entanto': 0,
             'tomar': 0,
             'rumo': 0,
             'obscuro': 0,
             'preservar': 0,
             'aroma': 0,
             'definitivo': 0,
             'frustrada': 0,
             'babá': 0,
             'noite': 0,
             'fim': 0,
             'semana': 0,
             'sarah': 0,
             'imaginação': 0,
             'ativo': 0,
             'convocar': 0,
             'goblins': 0,
             'favorito': 0,
             'labirinto': 0,
             'meio-irmão': 0,
             'embora': 0,
             'toby': 0,
             'segui lo': 0,
             'conto': 0,
             'fada': 0,
             'resgatar ele': 0,
             'rei': 0,
             'duendes': 0,
             'trapaceiro': 0,
             'branco': 0,
             'basquete': 0,
             'uner': 0,
             'dobrar': 0,
             'chance': 0,
             'quadra': 0,
             'rua': 0,
             'torneio': 0,
             'meia': 0,
             'idade': 0,
             'pouco': 0,
             'ex-mulher': 0,
             'amor': 0,
             'se': 0,
             'vampiro': 0,
             'lendário': 0,
             'caçador': 0,
             'recompensa': 0,
             'contratar': 0,
             'trazê-la': 0,
             'designar': 0,
             'branca': 0,
             'charlie': 0,
             'cão': 0,
             'serviço': 0,
             'licença': 0,
             'maternidade': 0,
             'tj': 0,
             '12': 0,
             'devido': 0,
             'alto': 0,
             'perfil': 0,

In [73]:
#fazer o mesmo para um dataframe de tf
list_dict_tfs = []
#corre-se cada documento
for document in list_dict_documents:
    #soma a quantidade de tokens do documento
    sum_document = sum([x for x in document.values()])
    #cria-se um dict de
    dict_doct = defaultdict(int)
    for key in document.keys():
        #fazer a conta da quantidade daquela palavra especifica em relacao a ao total de palavras
        dict_doct[key] = document[key]/sum_document

    #adiciona no final para criar o dataframe
    list_dict_tfs.append(dict_doct)

In [70]:
#criar o dataframe
df_tf = pd.DataFrame(list_dict_tfs)
df_tf

,história,primeiro,grande,batalha,fase,americano,guerra,vietnã,soldado,ambos,...,neverland,pan,escrita,j.m.,barrie,sylvia,wilder,lemmon,matthau,esgotado
0,0.083333,0.083333,0.083333,0.083333,0.083333,0.083333,0.083333,0.083333,0.083333,0.083333,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2996,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2998,0.028571,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.057143,0.057143,0.028571,0.028571,0.057143,0.028571,0.000000,0.000000,0.000000,0.000000
2999,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.034483,0.034483,0.034483,0.034483

16 - Analyze the dataframe above and answer: What is the importance of a given TF for the analyzed document? And for the corpus?

In [34]:
#TF measures how often a word appears in a document, indicating its relevance within that text. It highlights important terms in a document.

17 - Consider the formula:

$$
IDF(t) = \log\left(\frac{N}{df(t)}\right)
$$

where:

(N) is the total number of documents in the corpus.

(df(t)) is the number of documents in which the term (t) appears at least once.

Use the dataframe created in exercise 10 to create a dataframe that, instead of presenting the count of a specific token in a given document, presents its IDF (Inverse Document Frequency), reflecting how informative each term is across the corpus.

In [76]:
list_dict_tfs[0]

defaultdict(int,
            {'história': 0.08333333333333333,
             'primeiro': 0.08333333333333333,
             'grande': 0.08333333333333333,
             'batalha': 0.08333333333333333,
             'fase': 0.08333333333333333,
             'americano': 0.08333333333333333,
             'guerra': 0.08333333333333333,
             'vietnã': 0.08333333333333333,
             'soldado': 0.08333333333333333,
             'ambos': 0.08333333333333333,
             'lado': 0.08333333333333333,
             'travar': 0.08333333333333333,
             'negócio': 0.0,
             'droga': 0.0,
             'dar': 0.0,
             'errar': 0.0,
             'deixar': 0.0,
             'corpo': 0.0,
             'xerife': 0.0,
             'atirar': 0.0,
             'vice': 0.0,
             'dinheiro': 0.0,
             'amnésico': 0.0,
             'ferir': 0.0,
             'fugir': 0.0,
             '3.000.000': 0.0,
             'dea': 0.0,
             'investigar': 0.0,
             'assim': 0.0,
             'traficante': 0.0,
             'pai': 0.0,
             'deputado': 0.0,
             'matar': 0.0,
             'disc': 0.0,
             'jockey': 0.0,
             'grant': 0.0,
             'mazzy': 0.0,
             'reportar': 0.0,
             'estação': 0.0,
             'rádio': 0.0,
             'porão': 0.0,
             'cidade': 0.0,
             'canadense': 0.0,
             'pontypool': 0.0,
             'pensar': 0.0,
             'apenas': 0.0,
             'dia': 0.0,
             'trabalho': 0.0,
             'ouver': 0.0,
             'relato': 0.0,
             'vírus': 0.0,
             'transformar': 0.0,
             'pessoa': 0.0,
             'zumbi': 0.0,
             'barricar': 0.0,
             'cabine': 0.0,
             'tentar': 0.0,
             'descobrir': 0.0,
             'maneira': 0.0,
             'alertar': 0.0,
             'ouvinte': 0.0,
             'sobre': 0.0,
             'improvável': 0.0,
             'modo': 0.0,
             'transmissão': 0.0,
             'parceiro': 0.0,
             'detetive': 0.0,
             'francisco': 0.0,
             'assassinar': 0.0,
             'terrorista': 0.0,
             'irlanda': 0.0,
             'norte': 0.0,
             'policial': 0.0,
             'juntar': 0.0,
             'esquadrão': 0.0,
             'antibombar': 0.0,
             'levá-los': 0.0,
             'justiça': 0.0,
             'adolescente': 0.0,
             'prodígio': 0.0,
             'tenso': 0.0,
             'entrar': 0.0,
             'faculdade': 0.0,
             'engenharia': 0.0,
             'ponta': 0.0,
             'sentir': 0.0,
             'estranho': 0.0,
             'aluno': 0.0,
             'despreocupar': 0.0,
             'professor': 0.0,
             'pretender': 0.0,
             'projeto': 0.0,
             'laser': 0.0,
             'arma': 0.0,
             'militar': 0.0,
             'excêntrico': 0.0,
             'colega': 0.0,
             'quarto': 0.0,
             'planejar': 0.0,
             'arruinar': 0.0,
             'plano': 0.0,
             'terra': 0.0,
             'alternativa': 0.0,
             'coringa': 0.0,
             'enganar': 0.0,
             'superman': 0.0,
             'lois': 0.0,
             'lane': 0.0,
             'causar': 0.0,
             'agitação': 0.0,
             'herói': 0.0,
             'decidir': 0.0,
             'assumir': 0.0,
             'controle': 0.0,
             'batman': 0.0,
             'aliado': 0.0,
             'detê-lo': 0.0,
             'tim': 0.0,
             'robbins': 0.0,
             'chamar': 0.0,
             'trabalhar': 0.0,
             'dois': 0.0,
             'menino': 0.0,
             'walter': 0.0,
             'josh': 0.0,
             'hutcherson': 0.0,
             'danny': 0.0,
             'jonah': 0.0,
             'bobo': 0.0,
             'cuidado': 0.0,
             'irmã': 0.0,
             'lisa': 0.0,
             'kristen': 0.0,
             'stewart': 0.0,
             'dever': 0.0,
             'ficar': 0.0,
             'dentro': 0.0,
             'casa': 0.0,
             'antecipar': 0.0,
             'chato': 0.0,
             'chocado': 0.0,
             'começar': 0.0,
             'jogar': 0.0,
             'zathura': 0.0,
             'jogo': 0.0,
             'tabuleiro': 0.0,
             'tema': 0.0,
             'espacial': 0.0,
             'perceber': 0.0,
             'ter': 0.0,
             'poder': 0.0,
             'místico': 0.0,
             'lançar': 0.0,
             'espaço': 0.0,
             'ajuda': 0.0,
             'astronauta': 0.0,
             'dax': 0.0,
             'shepard': 0.0,
             'voltar': 0.0,
             'após': 0.0,
             'colapso': 0.0,
             'nervoso': 0.0,
             'tentativa': 0.0,
             'suicídio': 0.0,
             'ator': 0.0,
             'envelhecido': 0.0,
             'envolver': 0.0,
             'mulher': 0.0,
             'jovem': 0.0,
             'logo': 0.0,
             'difícil': 0.0,
             'acompanhar ela': 0.0,
             'dan': 0.0,
             'kristi': 0.0,
             'boas-vinda': 0.0,
             'bebê': 0.0,
             'recém-nascido': 0.0,
             'presença': 0.0,
             'demoníaco': 0.0,
             'aterrorizá lós': 0.0,
             'destruir': 0.0,
             'mundo': 0.0,
             'perfeito': 0.0,
             'transformar ele': 0.0,
             'pesadelo': 0.0,
             'inevitável': 0.0,
             'câmera': 0.0,
             'segurança': 0.0,
             'capturar': 0.0,
             'tormento': 0.0,
             'tornar': 0.0,
             'cada': 0.0,
             'minuto': 0.0,
             'terrivelmente': 0.0,
             'real': 0.0,
             'três': 0.0,
             'trapalhão': 0.0,
             'reservista': 0.0,
             'exército': 0.0,
             'destino': 0.0,
             'iraque': 0.0,
             'acidentalmente': 0.0,
             'vilarejo': 0.0,
             'mexicano': 0.0,
             'sitiar': 0.0,
             'força': 0.0,
             'hostil': 0.0,
             'giro': 0.0,
             'torno': 0.0,
             'cego': 0.0,
             'mohammed': 0.0,
             'liberar': 0.0,
             'escola': 0.0,
             'especial': 0.0,
             'teerã': 0.0,
             'férias': 0.0,
             'verão': 0.0,
             'envergonhar': 0.0,
             'oprimido': 0.0,
             'cegueira': 0.0,
             'chegar': 0.0,
             'atrasado': 0.0,
             'buscar ele': 0.0,
             'convencer': 0.0,
             'diretor': 0.0,
             'durante': 0.0,
             'recusar': 0.0,
             'então': 0.0,
             'acabar': 0.0,
             'levar ele': 0.0,
             'futuro': 0.0,
             'pós-apocalíptico': 0.0,
             'gangue': 0.0,
             'rival': 0.0,
             'lutar': 0.0,
             'frazier': 0.0,
             'park': 0.0,
             'beat': 0.0,
             'revelation': 0.0,
             'versão': 0.0,
             'mortal': 0.0,
             'dance': 0.0,
             'revolution(tm': 0.0,
             'criminoso': 0.0,
             'inexperiente': 0.0,
             'ben': 0.0,
             'assaltar': 0.0,
             'restaurante': 0.0,
             'pequeno': 0.0,
             'roubo': 0.0,
             'mal': 0.0,
             'crise': 0.0,
             'refém': 0.0,
             'presa': 0.0,
             'namorada': 0.0,
             'empresária': 0.0,
             'adie': 0.0,
             'graham': 0.0,
             'sociopata': 0.0,
             'astuto': 0.0,
             'comunidade': 0.0,
             'sombrio': 0.0,
             'temente': 0.0,
             'deus': 0.0,
             'abalar': 0.0,
             'assassinato': 0.0,
             'criança': 0.0,
             'psicóloga': 0.0,
             'examinar': 0.0,
             'dorothy': 0.0,
             'mills': 0.0,
             'acusar': 0.0,
             'crime': 0.0,
             'apesar': 0.0,
             'resistência': 0.0,
             'morador': 0.0,
             'terapeuta': 0.0,
             'suspeito': 0.0,
             'sofra': 0.0,
             'transtorno': 0.0,
             'personalidade': 0.0,
             'múltiplo': 0.0,
             '...': 0.0,
             'julho': 0.0,
             '1969': 0.0,
             'corrida': 0.0,
             'terminar': 0.0,
             'apollo': 0.0,
             '11': 0.0,
             'cumprir': 0.0,
             'desafio': 0.0,
             'presidente': 0.0,
             'kennedy': 0.0,
             '“': 0.0,
             'pousar': 0.0,
             'homem': 0.0,
             'lua': 0.0,
             'trazê-lo': 0.0,
             'volta': 0.0,
             'salvo': 0.0,
             '”': 0.0,
             'ninguém': 0.0,
             'testemunhar': 0.0,
             'pouso': 0.0,
             'lunar': 0.0,
             'jamais': 0.0,
             'esquecer': 0.0,
             'documentário': 0.0,
             'al': 0.0,
             'reinert': 0.0,
             'all': 0.0,
             'mankind': 0.0,
             'vinte': 0.0,
             'quatro': 0.0,
             'viajar': 0.0,
             'contar': 0.0,
             'palavra': 0.0,
             'voz': 0.0,
             'usar': 0.0,
             'imagem': 0.0,
             'experiência': 0.0,
             'quarenta': 0.0,
             'ano': 0.0,
             'continuar': 0.0,
             'ser': 0.0,
             'obra': 0.0,
             'cinema': 0.0,
             'radical': 0.0,
             'visualmente': 0.0,
             'deslumbrante': 0.0,
             'fazer': 0.0,
             'evento': 0.0,
             'costeiro': 0.0,
             'russo': 0.0,
             'kolya': 0.0,
             'forçar': 0.0,
             'contra': 0.0,
             'prefeito': 0.0,
             'corrupto': 0.0,
             'informar': 0.0,
             'demoler': 0.0,
             'recrutar': 0.0,
             'amigo': 0.0,
             'advogado': 0.0,
             'ajudar': 0.0,
             'chegada': 0.0,
             'trazer': 0.0,
             'infortúnio': 0.0,
             'família': 0.0,
             'clássico': 0.0,
             'romance': 0.0,
             'jane': 0.0,
             'austen': 0.0,
             'preconceito': 0.0,
             'ocorrir': 0.0,
             'classe': 0.0,
             'século': 0.0,
             'xix': 0.0,
             'orgulho': 0.0,
             'separar': 0.0,
             'amante': 0.0,
             'abusar': 0.0,
             'mentalmente': 0.0,
             'escravizar': 0.0,
             'coager': 0.0,
             'prostituição': 0.0,
             'impiedoso': 0.0,
             'morrer': 0.0,
             'missão': 0.0,
             'diretamente': 0.0,
             'espancar': 0.0,
             'pecador': 0.0,
             'santa': 0.0,
             'estritamente': 0.0,
             'pessoal': 0.0,
             'prisioneiro': 0.0,
             'vigilante': 0.0,
             'notório': 0.0,
             'gângster': 0.0,
             'pat': 0.0,
             'tate': 0.0,
             'sobir': 0.0,
             'hierarquia': 0.0,
             'submundo': 0.0,
             'essex': 0.0,
             'prequela': 0.0,
             'franquia': 0.0,
             'rise': 0.0,
             'of': 0.0,
             'the': 0.0,
             'footsoldier': 0.0,
             'casai': 0.0,
             'interior': 0.0,
             'texas': 0.0,
             'busca': 0.0,
             'lenda': 0.0,
             'urbano': 0.0,
             'bizarro': 0.0,
             'sádico': 0.0,
             'assassino': 0.0,
             'série': 0.0,
             'perseguição': 0.0,
             'caçar': 0.0,
             'temido': 0.0,
             'próprio': 0.0,
             'agenda': 0.0,
             'secreto': 0.0,
             'vida': 0.0,
             'ícone': 0.0,
             'música': 0.0,
             'elvis': 0.0,
             'presley': 0.0,
             'desde': 0.0,
             'infância': 0.0,
             'estrela': 0.0,
             'rock': 0.0,
             'década': 0.0,
             '1950': 0.0,
             'manter': 0.0,
             'relacionamento': 0.0,
             'complexo': 0.0,
             'empresário': 0.0,
             'coronel': 0.0,
             'tom': 0.0,
             'parker': 0.0,
             'paciente': 0.0,
             'câncer': 0.0,
             'iniciar': 0.0,
             'jornada': 0.0,
             'afirmação': 0.0,
             'visitar': 0.0,
             'autor': 0.0,
             'recluso': 0.0,
             'amsterdã': 0.0,
             'solteira': 0.0,
             'meia-idade': 0.0,
             'belo': 0.0,
             'irene': 0.0,
             'margarita': 0.0,
             'buy': 0.0,
             'totalmente': 0.0,
             'dedicar': 0.0,
             'inspetora': 0.0,
             'hotel': 0.0,
             'luxo': 0.0,
             'constantemente': 0.0,
             'estrada': 0.0,
             'entregar': 0.0,
             'prazer': 0.0,
             'caro': 0.0,
             'resort': 0.0,
             'impecável': 0.0,
             'sempre': 0.0,
             'incógnita': 0.0,
             'sozinha': 0.0,
             'escapar': 0.0,
             'próximo': 0.0,
             'exótico': 0.0,
             'lista': 0.0,
             'verificação': 0.0,
             'laptop': 0.0,
             'reboque': 0.0,
             'bom': 0.0,
             'ex': 0.0,
             'andrea': 0.0,
             'stefano': 0.0,
             'accorsi': 0.0,
             'fonte': 0.0,
             'apoio': 0.0,
             'emocional': 0.0,
             'repente': 0.0,
             'indisponível': 0.0,
             'profundo': 0.0,
             'existencial': 0.0,
             'forma': 0.0,
             'engano': 0.0,
             'dizer': 0.0,
             'companheiro': 0.0,
             'viagem': 0.0,
             'névoa': 0.0,
             'sauna': 0.0,
             'vapor': 0.0,
             'significado': 0.0,
             'disfarçar': 0.0,
             'derrubar': 0.0,
             'organização': 0.0,
             'parte': 0.0,
             'minissérie': 0.0,
             'dinamarquês': 0.0,
             'editar': 0.0,
             'filme': 0.0,
             'riget': 0.0,
             'passar': 0.0,
             'ala': 0.0,
             'neurocirúrgico': 0.0,
             'rigshospitalet': 0.0,
             'copenhague': 0.0,
             'principal': 0.0,
             'hospital': 0.0,
             'país': 0.0,
             'apelidar': 0.0,
             'show': 0.0,
             'seguir': 0.0,
             'personagem': 0.0,
             'tanto': 0.0,
             'funcionário': 0.0,
             'quanto': 0.0,
             'enquanto': 0.0,
             'encontrar': 0.0,
             'fenômeno': 0.0,
             'humano': 0.0,
             'sobrenatural': 0.0,
             'aparecer': 0.0,
             'estimar': 0.0,
             'livro': 0.0,
             '1001': 0.0,
             'ver': 0.0,
             'antes': 0.0,
             'fronteira': 0.0,
             'expedição': 0.0,
             'comércio': 0.0,
             'pele': 0.0,
             '1820': 0.0,
             'luta': 0.0,
             'sobrevivência': 0.0,
             'atacar': 0.0,
             'urso': 0.0,
             'membro': 0.0,
             'equipe': 0.0,
             'caça': 0.0,
             'tyler': 0.0,
             'rake': 0.0,
             'destemido': 0.0,
             'mercenário': 0.0,
             'mercado': 0.0,
             'negro': 0.0,
             'embarcar': 0.0,
             'extração': 0.0,
             'carreira': 0.0,
             'alistar': 0.0,
             'resgatar': 0.0,
             'filho': 0.0,
             'sequestrar': 0.0,
             'internacional': 0.0,
             'preso': 0.0,
             'vigarista': 0.0,
             'rural': 0.0,
             'desertor': 0.0,
             'habitante': 0.0,
             'garota': 0.0,
             'rico': 0.0,
             'proteger': 0.0,
             'dupla': 0.0,
             'fuga': 0.0,
             'ira': 0.0,
             'perseguir': 0.0,
             'todo': 0.0,
             'viúva': 0.0,
             'filha': 0.0,
             'outro': 0.0,
             'preparar': 0.0,
             'tudo': 0.0,
             'novo': 0.0,
             'alice': 0.0,
             'palmer': 0.0,
             '16': 0.0,
             'afogar': 0.0,
             'represa': 0.0,
             'local': 0.0,
             'recuperar': 0.0,
             'enlutar': 0.0,
             'enterra': 0.0,
             'inexplicável': 0.0,
             '\u200b\u200bcentrar': 0.0,
             'redor': 0.0,
             'inquietos': 0.0,
             'palmers': 0.0,
             'procurar': 0.0,
             'médium': 0.0,
             'parapsicólogo': 0.0,
             'ray': 0.0,
             'kemeny': 0.0,
             'levar': 0.0,
             'duplo': 0.0,
             'lago': 0.0,
             'mungo': 0.0,
             'passado': 0.0,
             'emerger': 0.0,
             'despejar': 0.0,
             'apartamento': 0.0,
             'manhattan': 0.0,
             'casal': 0.0,
             'comprar': 0.0,
             'parecer': 0.0,
             'sonho': 0.0,
             'sobrecarregado': 0.0,
             'esvaziamento': 0.0,
             'conta': 0.0,
             'bancário': 0.0,
             'lutando': 0.0,
             'junto': 0.0,
             'mansão': 0.0,
             'desconexar': 0.0,
             'desmorona': 0.0,
             'assistir': 0.0,
             'horror': 0.0,
             'hilário': 0.0,
             'incluir': 0.0,
             'pia': 0.0,
             'cozinha': 0.0,
             'desaparecer': 0.0,
             'poço': 0.0,
             'longo': 0.0,
             'data': 0.0,
             'will': 0.0,
             'bryan': 0.0,
             'matt': 0.0,
             'corey': 0.0,
             'amado': 0.0,
             'avô': 0.0,
             'inesperadamente': 0.0,
             'reivindicar': 0.0,
             'herança': 0.0,
             'turma': 0.0,
             'conhecer': 0.0,
             'prima': 0.0,
             'jessie': 0.0,
             'hilariante': 0.0,
             'ler': 0.0,
             'virar': 0.0,
             'cabeça': 0.0,
             'baixo': 0.0,
             'esposo': 0.0,
             'max': 0.0,
             'simkin': 0.0,
             'consertar': 0.0,
             'sapato': 0.0,
             'mesmo': 0.0,
             'loja': 0.0,
             'nova': 0.0,
             'york': 0.0,
             'geração': 0.0,
             'desiludido': 0.0,
             'rotina': 0.0,
             'diário': 0.0,
             'deparar': 0.0,
             'mágico': 0.0,
             'permitir': 0.0,
             'cliente': 0.0,
             'vez': 0.0,
             'colocar se': 0.0,
             'lugar': 0.0,
             'único': 0.0,
             'realmente': 0.0,
             'participar': 0.0,
             'poderoso': 0.0,
             'experimento': 0.0,
             'médico': 0.0,
             'ganhar': 0.0,
             'habilidade': 0.0,
             'telepático': 0.0,
             'pirocinético': 0.0,
             'exploração': 0.0,
             'nação': 0.0,
             'tecnologicamente': 0.0,
             'desenvolvimento': 0.0,
             'efeito': 0.0,
             'transição': 0.0,
             'modernização': 0.0,
             'estilo': 0.0,
             'ocidental': 0.0,
             'jean-baptiste': 0.0,
             'grenouille': 0.0,
             'nascer': 0.0,
             'fedor': 0.0,
             'paris': 0.0,
             '18': 0.0,
             'desenvolver': 0.0,
             'sentido': 0.0,
             'olfativo': 0.0,
             'superior': 0.0,
             'criar': 0.0,
             'perfume': 0.0,
             'entanto': 0.0,
             'tomar': 0.0,

In [92]:
import math

#calculate idf of word guerra
N = len(list_dict_documents)
token = "guerra"
#how many documents guerra appear
count_appear = 0
#for each document
for x in list_dict_documents:
    if x[token] >= 1:
        count_appear += 1

#idf
idf_guerra = N/count_appear
print(idf_guerra)

#or log
print(math.log10(idf_guerra))

18.181818181818183
1.2596373105057561

In [90]:
#now tf-idf of guerra for the first document
#get tf fom df
print(list_dict_tfs[0]["guerra"])
print(idf_guerra)

#tf-idf
print(list_dict_tfs[0]["guerra"]*idf_guerra)

0.08333333333333333
18.181818181818183
1.5151515151515151